version: "3"
networks:
  comms-network:
    driver: bridge

services:
  comms-api:
    image: comms-api
    container_name: comms-api
    build:
      context: ./comms-api/
      dockerfile: dockerfile
    ports:
      # Can specify only container port and a random host port will be chosen
      # HostPort:ContainerPort
      - "8081:8081" 
    hostname: comms-api
    networks:
      - comms-network

  comms-client:
    image: comms-client
    container_name: comms-client
    build:
      context: ./comms-client/
      dockerfile: dockerfile
    hostname: comms-client
    ports:
      - "4200:4200"
    networks:
      - comms-network